### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'MODEL_IMG'

### ISSUE THREAD

**Issue by Baymax1520301** [Cc-Hy/CMKD#60]
2024-05-20 13:07:04.828611: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-20 13:07:04.884111: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-20 13:07:05.763789: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-05-20 13:07:06,799   INFO  **********************Start logging**********************
2024-05-20 13:07:06,799   INFO  CUDA_VISIBLE_DEVICES=ALL
2024-05-20 13:07:06,799   INFO  cfg_file         cfgs/kitti_models/pointpillar.yaml
2024-05-20 13:07:06,799   INFO  batch_size       4
2024-05-20 13:07:06,799   INFO  epochs           80
2024-05-20 13:07:06,799   INFO  workers          12
2024-05-20 13:07:06,799   INFO  extra_tag        default
2024-05-20 13:07:06,799   INFO  ckpt             None
2024-05-20 13:07:06,799   INFO  launcher         none
2024-05-20 13:07:06,799   INFO  tcp_port         18866
2024-05-20 13:07:06,799   INFO  sync_bn          False
2024-05-20 13:07:06,799   INFO  fix_random_seed  False
2024-05-20 13:07:06,799   INFO  ckpt_save_interval 1
2024-05-20 13:07:06,799   INFO  local_rank       0
2024-05-20 13:07:06,799   INFO  max_ckpt_save_num 20
2024-05-20 13:07:06,799   INFO  start_save_epoch 0
2024-05-20 13:07:06,799   INFO  merge_all_iters_to_one_epoch False
2024-05-20 13:07:06,799   INFO  set_cfgs         None
2024-05-20 13:07:06,799   INFO  max_waiting_mins 0
2024-05-20 13:07:06,800   INFO  start_epoch      0
2024-05-20 13:07:06,800   INFO  save_to_file     False
2024-05-20 13:07:06,800   INFO  pretrained_img_model None
2024-05-20 13:07:06,800   INFO  pretrained_lidar_model checkpoints/pp-teacher-kitti.pth
2024-05-20 13:07:06,800   INFO  use_lidar_head   False
2024-05-20 13:07:06,800   INFO  format_only      False
2024-05-20 13:07:06,800   INFO  cfg.ROOT_DIR: /root/autodl-tmp/CMKD
2024-05-20 13:07:06,800   INFO  cfg.LOCAL_RANK: 0
2024-05-20 13:07:06,800   INFO  cfg.CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']
2024-05-20 13:07:06,800   INFO  
cfg.DATA_CONFIG = edict()
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.DATASET: KittiDataset
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.DATA_PATH: ../data/kitti
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]
2024-05-20 13:07:06,800   INFO  
cfg.DATA_CONFIG.DATA_SPLIT = edict()
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.DATA_SPLIT.train: train
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.DATA_SPLIT.test: val
2024-05-20 13:07:06,800   INFO  
cfg.DATA_CONFIG.INFO_PATH = edict()
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.INFO_PATH.train: ['kitti_infos_train.pkl']
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.INFO_PATH.test: ['kitti_infos_val.pkl']
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.GET_ITEM_LIST: ['points']
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.FOV_POINTS_ONLY: True
2024-05-20 13:07:06,800   INFO  
cfg.DATA_CONFIG.DATA_AUGMENTOR = edict()
2024-05-20 13:07:06,800   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.DISABLE_AUG_LIST: ['placeholder']
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.AUG_CONFIG_LIST: [{'NAME': 'gt_sampling', 'USE_ROAD_PLANE': True, 'DB_INFO_PATH': ['kitti_dbinfos_train.pkl'], 'PREPARE': {'filter_by_min_points': ['Car:5', 'Pedestrian:5', 'Cyclist:5'], 'filter_by_difficulty': [-1]}, 'SAMPLE_GROUPS': ['Car:15', 'Pedestrian:15', 'Cyclist:15'], 'NUM_POINT_FEATURES': 4, 'DATABASE_WITH_FAKELIDAR': False, 'REMOVE_EXTRA_WIDTH': [0.0, 0.0, 0.0], 'LIMIT_WHOLE_SCENE': False}, {'NAME': 'random_world_flip', 'ALONG_AXIS_LIST': ['x']}, {'NAME': 'random_world_rotation', 'WORLD_ROT_ANGLE': [-0.78539816, 0.78539816]}, {'NAME': 'random_world_scaling', 'WORLD_SCALE_RANGE': [0.95, 1.05]}]
2024-05-20 13:07:06,801   INFO  
cfg.DATA_CONFIG.POINT_FEATURE_ENCODING = edict()
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.encoding_type: absolute_coordinates_encoding
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.used_feature_list: ['x', 'y', 'z', 'intensity']
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.src_feature_list: ['x', 'y', 'z', 'intensity']
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG.DATA_PROCESSOR: [{'NAME': 'mask_points_and_boxes_outside_range', 'REMOVE_OUTSIDE_BOXES': True}, {'NAME': 'shuffle_points', 'SHUFFLE_ENABLED': {'train': True, 'test': False}}, {'NAME': 'transform_points_to_voxels', 'VOXEL_SIZE': [0.16, 0.16, 4], 'MAX_POINTS_PER_VOXEL': 32, 'MAX_NUMBER_OF_VOXELS': {'train': 16000, 'test': 40000}}]
2024-05-20 13:07:06,801   INFO  cfg.DATA_CONFIG._BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml
2024-05-20 13:07:06,801   INFO  
cfg.MODEL = edict()
2024-05-20 13:07:06,801   INFO  cfg.MODEL.NAME: PointPillar
2024-05-20 13:07:06,801   INFO  
cfg.MODEL.VFE = edict()
2024-05-20 13:07:06,801   INFO  cfg.MODEL.VFE.NAME: PillarVFE
2024-05-20 13:07:06,801   INFO  cfg.MODEL.VFE.WITH_DISTANCE: False
2024-05-20 13:07:06,801   INFO  cfg.MODEL.VFE.USE_ABSLOTE_XYZ: True
2024-05-20 13:07:06,801   INFO  cfg.MODEL.VFE.USE_NORM: True
2024-05-20 13:07:06,801   INFO  cfg.MODEL.VFE.NUM_FILTERS: [64]
2024-05-20 13:07:06,801   INFO  
cfg.MODEL.MAP_TO_BEV = edict()
2024-05-20 13:07:06,801   INFO  cfg.MODEL.MAP_TO_BEV.NAME: PointPillarScatter
2024-05-20 13:07:06,801   INFO  cfg.MODEL.MAP_TO_BEV.NUM_BEV_FEATURES: 64
2024-05-20 13:07:06,801   INFO  
cfg.MODEL.BACKBONE_2D = edict()
2024-05-20 13:07:06,801   INFO  cfg.MODEL.BACKBONE_2D.NAME: BaseBEVBackbone
2024-05-20 13:07:06,801   INFO  cfg.MODEL.BACKBONE_2D.LAYER_NUMS: [3, 5, 5]
2024-05-20 13:07:06,801   INFO  cfg.MODEL.BACKBONE_2D.LAYER_STRIDES: [2, 2, 2]
2024-05-20 13:07:06,801   INFO  cfg.MODEL.BACKBONE_2D.NUM_FILTERS: [64, 128, 256]
2024-05-20 13:07:06,801   INFO  cfg.MODEL.BACKBONE_2D.UPSAMPLE_STRIDES: [1, 2, 4]
2024-05-20 13:07:06,802   INFO  cfg.MODEL.BACKBONE_2D.NUM_UPSAMPLE_FILTERS: [128, 128, 128]
2024-05-20 13:07:06,802   INFO  
cfg.MODEL.DENSE_HEAD = edict()
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.NAME: AnchorHeadSingle
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.CLASS_AGNOSTIC: False
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.USE_DIRECTION_CLASSIFIER: True
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.DIR_OFFSET: 0.78539
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.DIR_LIMIT_OFFSET: 0.0
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.NUM_DIR_BINS: 2
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.ANCHOR_GENERATOR_CONFIG: [{'class_name': 'Car', 'anchor_sizes': [[3.9, 1.6, 1.56]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.6, 'unmatched_threshold': 0.45}, {'class_name': 'Pedestrian', 'anchor_sizes': [[0.8, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-0.6], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}, {'class_name': 'Cyclist', 'anchor_sizes': [[1.76, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-0.6], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}]
2024-05-20 13:07:06,802   INFO  
cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG = edict()
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NAME: AxisAlignedTargetAssigner
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.POS_FRACTION: -1.0
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.SAMPLE_SIZE: 512
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NORM_BY_NUM_EXAMPLES: False
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.MATCH_HEIGHT: False
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.BOX_CODER: ResidualCoder
2024-05-20 13:07:06,802   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG = edict()
2024-05-20 13:07:06,802   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.cls_weight: 1.0
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.loc_weight: 2.0
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.dir_weight: 0.2
2024-05-20 13:07:06,802   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2024-05-20 13:07:06,802   INFO  
cfg.MODEL.POST_PROCESSING = edict()
2024-05-20 13:07:06,802   INFO  cfg.MODEL.POST_PROCESSING.RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.SCORE_THRESH: 0.1
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.OUTPUT_RAW_SCORE: False
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.EVAL_METRIC: kitti
2024-05-20 13:07:06,803   INFO  
cfg.MODEL.POST_PROCESSING.NMS_CONFIG = edict()
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.MULTI_CLASSES_NMS: False
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_TYPE: nms_gpu
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_THRESH: 0.01
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_PRE_MAXSIZE: 4096
2024-05-20 13:07:06,803   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_POST_MAXSIZE: 500
2024-05-20 13:07:06,803   INFO  
cfg.OPTIMIZATION = edict()
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.BATCH_SIZE_PER_GPU: 4
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.NUM_EPOCHS: 80
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.OPTIMIZER: adam_onecycle
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.LR: 0.003
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.WEIGHT_DECAY: 0.01
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.MOMENTUM: 0.9
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.MOMS: [0.95, 0.85]
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.PCT_START: 0.4
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.DIV_FACTOR: 10
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.DECAY_STEP_LIST: [35, 45]
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.LR_DECAY: 0.1
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.LR_CLIP: 1e-07
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.LR_WARMUP: False
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.WARMUP_EPOCH: 1
2024-05-20 13:07:06,803   INFO  cfg.OPTIMIZATION.GRAD_NORM_CLIP: 10
2024-05-20 13:07:06,804   INFO  cfg.TAG: pointpillar
2024-05-20 13:07:06,804   INFO  cfg.EXP_GROUP_PATH: kitti_models
2024-05-20 13:07:06,980   INFO  Database filter by min points Car: 14357 => 13532
2024-05-20 13:07:06,980   INFO  Database filter by min points Pedestrian: 2207 => 2168
2024-05-20 13:07:06,981   INFO  Database filter by min points Cyclist: 734 => 705
2024-05-20 13:07:07,001   INFO  Database filter by difficulty Car: 13532 => 10759
2024-05-20 13:07:07,005   INFO  Database filter by difficulty Pedestrian: 2168 => 2075
2024-05-20 13:07:07,006   INFO  Database filter by difficulty Cyclist: 705 => 581
2024-05-20 13:07:07,011   INFO  Loading KITTI dataset
2024-05-20 13:07:07,127   INFO  Total samples for KITTI dataset: 3712
Traceback (most recent call last):
  File "train_cmkd.py", line 219, in <module>
    main()
  File "train_cmkd.py", line 120, in main
    model.model_img = build_network(model_cfg=cfg.MODEL_IMG, num_class=len(cfg.CLASS_NAMES), dataset=train_set)
AttributeError: 'EasyDict' object has no attribute 'MODEL_IMG'

May I ask how to resolve this error?

**Comment by AlexandreDiPiazza** [comment]
Hi, 

Could you share the environement that you used to run the files? I couldnt manage to make the command: "python setup.py develop" work

**Comment by Baymax1520301** [comment]
> 您可以分享一下您用来运行文件的环境吗？

sure

**Comment by Baymax1520301** [comment]
> 你好，
> 
> 您可以分享一下您用来运行文件的环境吗？我无法使用命令：“python setup.pydevelop”工作

sure

absl-py                        1.4.0
addict                         2.4.0
anyio                          3.3.1
argon2-cffi                    21.1.0
array-record                   0.4.0
astunparse                     1.6.3
attrs                          21.2.0
Babel                          2.9.1
backcall                       0.2.0
black                          24.4.2
bleach                         4.1.0
brotlipy                       0.7.0
cachetools                     4.2.2
certifi                        2021.5.30
cffi                           1.14.6
chardet                        4.0.0
click                          8.1.7
cloudpickle                    3.0.0
cmake                          3.29.3
comm                           0.2.2
conda-package-handling         1.7.3
contourpy                      1.1.1
cryptography                   3.4.7
cycler                         0.10.0
Cython                         3.0.10
dacite                         1.8.1
dask                           2023.3.1
dataclass_array                1.4.1
debugpy                        1.8.1
decorator                      5.1.0
defusedxml                     0.7.1
descartes                      1.1.0
dm-tree                        0.1.8
easydict                       1.9
einops                         0.8.0
einsum                         0.3.0
entrypoints                    0.3
etils                          1.3.0
exceptiongroup                 1.2.1
filelock                       3.14.0
fire                           0.6.0
flake8                         7.0.0
flatbuffers                    24.3.25
fonttools                      4.51.0
fsspec                         2024.5.0
gast                           0.3.3
google-auth                    2.16.2
google-auth-oauthlib           1.0.0
google-pasta                   0.2.0
googleapis-common-protos       1.63.0
grpcio                         1.63.0
h5py                           2.10.0
idna                           2.10
imageio                        2.34.1
immutabledict                  2.2.0
importlib_metadata             7.1.0
importlib_resources            6.4.0
iniconfig                      2.0.0
ipykernel                      6.29.4
ipython                        7.27.0
ipython-genutils               0.2.0
ipywidgets                     7.6.5
jax                            0.4.13
jedi                           0.18.0
Jinja2                         3.0.1
joblib                         1.4.2
json5                          0.9.6
jsonschema                     3.2.0
jupyter                        1.0.0
jupyter-client                 7.0.3
jupyter-console                6.6.3
jupyter_core                   5.7.2
jupyter-server                 1.11.0
jupyterlab                     3.1.12
jupyterlab-language-pack-zh-CN 0.0.1.dev0
jupyterlab-pygments            0.1.2
jupyterlab-server              2.8.1
jupyterlab-widgets             1.0.2
keras                          2.12.0
Keras-Preprocessing            1.1.2
kiwisolver                     1.3.2
kornia                         0.7.2
kornia_rs                      0.1.3
lark                           1.1.9
lazy_loader                    0.4
libclang                       18.1.1
llvmlite                       0.31.0
locket                         1.0.0
lyft-dataset-sdk               0.0.8
Markdown                       3.3.4
MarkupSafe                     2.0.1
matplotlib                     3.6.1
matplotlib-inline              0.1.3
mccabe                         0.7.0
mistune                        0.8.4
ml-dtypes                      0.2.0
mmcv-full                      1.4.8
mmdet                          2.24.1        /root/autodl-tmp/mmdetection
mmdet3d                        0.17.1        /root/autodl-tmp/mmdetection3d
mmsegmentation                 0.20.2
mpmath                         1.3.0
mypy-extensions                1.0.0
nbclassic                      0.3.2
nbclient                       0.5.4
nbconvert                      6.1.0
nbformat                       5.1.3
nest-asyncio                   1.5.1
networkx                       3.1
notebook                       6.4.4
numba                          0.48.0
numpy                          1.23.0
nuscenes-devkit                1.1.10
nvidia-cublas-cu12             12.1.3.1
nvidia-cuda-cupti-cu12         12.1.105
nvidia-cuda-nvrtc-cu12         12.1.105
nvidia-cuda-runtime-cu12       12.1.105
nvidia-cudnn-cu12              8.9.2.26
nvidia-cufft-cu12              11.0.2.54
nvidia-curand-cu12             10.3.2.106
nvidia-cusolver-cu12           11.4.5.107
nvidia-cusparse-cu12           12.1.0.106
nvidia-nccl-cu12               2.20.5
nvidia-nvjitlink-cu12          12.4.127
nvidia-nvtx-cu12               12.1.105
oauthlib                       3.1.1
opencv-python                  4.9.0.80
OpenEXR                        1.3.9
opt-einsum                     3.3.0
ordered-set                    4.1.0
packaging                      22.0
pandas                         1.5.3
pandocfilters                  1.5.0
parso                          0.8.2
partd                          1.4.1
pathspec                       0.12.1
pcdet                          0.5.2+7649474 /root/autodl-tmp/CMKD
pexpect                        4.8.0
pickleshare                    0.7.5
Pillow                         9.2.0
pip                            24.0
platformdirs                   4.2.2
plotly                         5.13.1
pluggy                         1.5.0
plyfile                        1.0.3
prettytable                    3.10.0
prometheus-client              0.11.0
promise                        2.3
prompt-toolkit                 3.0.43
protobuf                       3.20.3
psutil                         5.9.8
ptyprocess                     0.7.0
pyarrow                        10.0.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pycocotools                    2.0.7
pycodestyle                    2.11.1
pycosat                        0.6.3
pycparser                      2.20
pyflakes                       3.2.0
Pygments                       2.10.0
pyOpenSSL                      20.0.1
pyparsing                      2.4.7
pyquaternion                   0.9.9
pyrsistent                     0.18.0
PySocks                        1.7.1
pytest                         8.2.0
python-dateutil                2.8.2
python-gflags                  3.1.2
pytz                           2021.1
PyWavelets                     1.4.1
PyYAML                         6.0.1
pyzmq                          26.0.3
qtconsole                      5.5.2
QtPy                           2.4.1
requests                       2.25.1
requests-oauthlib              1.3.0
requests-unixsocket            0.2.0
rsa                            4.7.2
ruamel-yaml-conda              0.15.100
scikit-image                   0.20.0
scikit-learn                   1.2.2
scipy                          1.9.1
Send2Trash                     1.8.0
setuptools                     67.6.0
Shapely                        1.8.5
SharedArray                    3.2.3
six                            1.16.0
sniffio                        1.2.0
spconv                         1.2.1
supervisor                     4.2.2
sympy                          1.12
tenacity                       8.3.0
tensorboard                    2.12.3
tensorboard-data-server        0.7.2
tensorboard-plugin-wit         1.8.0
tensorboardX                   2.6.2.2
tensorflow                     2.12.0
tensorflow-addons              0.21.0
tensorflow-datasets            4.9.2
tensorflow-estimator           2.12.0
tensorflow-graphics            2021.12.3
tensorflow-io-gcs-filesystem   0.34.0
tensorflow-metadata            1.14.0
tensorflow-probability         0.19.0
termcolor                      2.4.0
terminado                      0.12.1
terminaltables                 3.1.10
testpath                       0.5.0
threadpoolctl                  3.5.0
tifffile                       2023.7.10
toml                           0.10.2
tomli                          2.0.1
toolz                          0.12.1
torch                          1.9.0+cu111
torchaudio                     0.9.0
torchvision                    0.10.0+cu111
tornado                        6.1
tqdm                           4.61.2
traitlets                      5.14.3
trimesh                        4.4.0
triton                         2.3.0
typeguard                      2.13.3
typing_extensions              4.5.0
urllib3                        1.26.6
visu3d                         1.5.1
waymo-open-dataset-tf-2-12-0   1.6.4
wcwidth                        0.2.5
webencodings                   0.5.1
websocket-client               1.2.1
Werkzeug                       2.0.1
wheel                          0.36.2
widgetsnbextension             3.5.1
wrapt                          1.14.1
yapf                           0.40.2
zipp                           3.18.2

**Comment by Baymax1520301** [comment]
My problem has been resolved because I used the wrong config file
